#ifndef html_h
#define html_h

String main_page=
"<html>\r\n"
"    <head>\r\n"
"      <style>\r\n"
"        body { background-color: #202020; }\r\n"
"        h2, td, a { color: #95A5A6; }\r\n"
"        p { color: white; }\r\n"
"        a#settingsbutton { padding:0px 5px 0px 5px; border: 3px solid #d3d3d3; color: #95A5A6; font-size: 15px; font-style: bold; border-radius: 5px;background: #202020; text-decoration:none; }\r\n"
"        a#settingsbutton:hover { padding:0px 5px 0px 5px; border: 3px solid #d3d3d3; color: #111; font-size: 15px; font-style: bold; border-radius: 5px;background: #4CAF50; cursor: pointer;transition: transform 0.4s, color 0.4s, background-color 0.4s; text-decoration:none; }\r\n"
"      </style>\r\n"
"      <title>Aquarium Controller</title>\r\n"
"      <meta charset=\"utf-8\">\r\n"
"      <script src=//cdn.rawgit.com/Mikhus/canvas-gauges/gh-pages/download/2.1.5/all/gauge.min.js></script>\r\n"
"      <script src=\"//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n"
"      <script type=\"text/javascript\">\r\n"
"        $(document).ready(function () {\r\n"
"          setInterval(updateGauges, 1000);  \r\n"
"        })\r\n"
"        function updateGauges(){ \r\n"
"          $.ajax({ \r\n"
"            type: 'GET', \r\n"
"            contentType: 'application/json; charset=utf-8',\r\n"
"            url: '/fishtank.json', \r\n"
"            data: {}, \r\n"
"            dataType: 'json',\r\n"
"            success: function (data) { \r\n"
"                tempGauge.value=data.fishtankdata.temperature;\r\n"
"                pwmGauge.value=data.fishtankdata.fan_pwm/250*100;\r\n"
"            }\r\n"
"          });\r\n"
"        }\r\n"
"      </script>\r\n"
"    </head>\r\n"
"    <body>\r\n"
"        <h2>Aquarium Controller</h2>\r\n"
"    <table>\r\n"
"      <tr>\r\n"
"        <td align=\"center\"><strong>Temperature [C]</strong></td>\r\n"
"        <td align=\"center\"><strong>FAN Speed [%]</strong></td>\r\n"
"      <tr>\r\n"
"        <td><canvas id=\"temp_gauge\"></canvas></td>\r\n"
"        <td><canvas id=\"pwm_gauge\"></canvas></td>\r\n"
"      </tr>\r\n"
"      <tr>\r\n"
"        <td align=\"left\"><a id=\"settingsbutton\" href=\"/settings\"> settings </a></td>\r\n"
"        <td align=\"left\"></td>\r\n"
"      <tr>\r\n"
"    </table>\r\n"
"    <script type=\"text/javascript\">\r\n"
"      var pwmGauge = new RadialGauge({\r\n"
"        renderTo: 'pwm_gauge',\r\n"
"        height: 300,\r\n"
"        units: '%',\r\n"
"        minValue: 0,\r\n"
"        maxValue: 100,\r\n"
"        majorTicks: [\r\n"
"            '0',\r\n"
"            '10',\r\n"
"            '20',\r\n"
"            '30',\r\n"
"            '40',\r\n"
"            '50',\r\n"
"            '60',\r\n"
"            '70',\r\n"
"            '80',\r\n"
"            '90',\r\n"
"            '100'\r\n"
"        ],\r\n"
"        minorTicks: 2,\r\n"
"        valueBox: true,\r\n"
"        animationDuration: 1500,\r\n"
"        animationRule: \"dequint\",\r\n"
"        animatedValue: true\r\n"
"      });\r\n"
"      pwmGauge.draw();\r\n"
"      pwmGauge.value = \"0\";\r\n"
"\r\n"
"      var tempGauge = new RadialGauge({\r\n"
"        renderTo: 'temp_gauge',\r\n"
"        height: 300,\r\n"
"        units: '°C',\r\n"
"        minValue: 20,\r\n"
"        maxValue: 35,\r\n"
"        majorTicks: [\r\n"
"            '20',\r\n"
"            '21',\r\n"
"            '22',\r\n"
"            '23',\r\n"
"            '24',\r\n"
"            '25',\r\n"
"            '26',\r\n"
"            '27',\r\n"
"            '28',\r\n"
"            '29',\r\n"
"            '30',\r\n"
"            '31',\r\n"
"            '32',\r\n"
"            '33',\r\n"
"            '34',\r\n"
"            '35'\r\n"
"        ],\r\n"
"        minorTicks: 5,\r\n"
"        highlights  : [\r\n"
"          {from: 24, to: 26, color: 'rgba(50, 200, 50, .75)'},\r\n"
"          {from: 22, to: 24, color: 'rgba(255, 140, 50, .75)'},\r\n"
"          {from: 20, to: 22, color: 'rgba(255, 50, 50, .75)'},\r\n"
"          {from: 26, to: 28, color: 'rgba(255, 140, 50, .75)'},\r\n"
"          {from: 28, to: 35, color: 'rgba(255, 50, 50, .75)'}\r\n"
"        ],\r\n"
"        valueBox: true,\r\n"
"        animationDuration: 1500,\r\n"
"        animationRule: \"dequint\",\r\n"
"        animatedValue: true\r\n"
"      });\r\n"
"      tempGauge.draw();\r\n"
"      tempGauge.value = \"0\";\r\n"
"    </script>\r\n"
"  </body>\r\n"
"</html>\r\n";

String settings_page=
"<html>\r\n"
"    <head>\r\n"
"      <style>\r\n"
"        html { font-family: \"Gudea\", Helvetica, sans-serif; height: 100%; }\r\n"
"        body { background-color: #202020; }\r\n"
"        h2, td, a { color: #95A5A6; }\r\n"
"        p { color: white; }\r\n"
"        td { padding-bottom: 5px; }\r\n"
"        .slidecontainer { width: 50%; }\r\n"
"        .slider { -webkit-appearance: none; appearance: none; width: 100%; height: 15px; border-radius: 5px; background: #d3d3d3; outline: none; opacity: 0.7; -webkit-transition: .2s; transition: opacity .2s; }\r\n"
"        .slider:hover { opacity: 1; }\r\n"
"        .slider::-webkit-slider-thumb { -webkit-appearance: none; appearance: none; width: 25px; height: 25px; border-radius: 50%; background: #4CAF50;  cursor: pointer; }\r\n"
"        .slider::-moz-range-thumb { width: 25px; height: 25px; border-radius: 50%; background: #4CAF50; cursor: pointer; }\r\n"
"        .switch { position: relative; margin: 0px auto; width: 270px; height: 20px; border: 3px solid #d3d3d3; color: #95A5A6; font-size: 15px; border-radius: 5px; }\r\n"
"        .mode { position: relative; display: inline-block; width: 33.3%; height: 100%; line-height: 20px; }\r\n"
"        .mode:first-child label { border-radius: 2px 0 0 2px; }\r\n"
"        .mode:last-child label { border-radius: 0 2px 2px 0; }\r\n"
"        .mode label { position: absolute; top: 0; left: 0; width: 100%; height: 100%; cursor: pointer; font-style: bold; text-align: center; transition: transform 0.4s, color 0.4s, background-color 0.4s; }\r\n"
"        .mode input[type=\"radio\"] { appearance: none; width: 0; height: 0; opacity: 0; }\r\n"
"        .mode input[type=\"radio\"]:focus { outline: 0; outline-offset: 0; }\r\n"
"        .mode input[type=\"radio\"]:checked ~ label { background-color: #4CAF50; color: #111; }\r\n"
"        .mode input[type=\"radio\"]:active ~ label { transform: scale(1.05); }\r\n"
"        a#backbutton, input[type=submit] { border: 3px solid #d3d3d3; color: #95A5A6; font-size: 15px; font-style: bold; border-radius: 5px;background: #202020; text-decoration:none; }\r\n"
"        a#backbutton:hover, input[type=submit]:hover { border: 3px solid #d3d3d3; color: #111; font-size: 15px; font-style: bold; border-radius: 5px;background: #4CAF50; cursor: pointer;transition: transform 0.4s, color 0.4s, background-color 0.4s; text-decoration:none; }\r\n"
"        a#backbutton, a#backbutton:hover{ padding:0px 5px 0px 5px; }\r\n"
"      </style>\r\n"
"      <title>Aquarium Controller</title>\r\n"
"      <meta charset=\"utf-8\">\r\n"
"      <script src=\"//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n"
"      <script type=\"text/javascript\">\r\n"
"        $(document).ready(function () {\r\n"
"          var desiredTemp = document.getElementById(\"desired_temp\");\r\n"
"          var valueDesiredTemp = document.getElementById(\"desired_temp_value\");\r\n"
"          var tempOffset = document.getElementById(\"temp_offset\");\r\n"
"          var valueTempOffset = document.getElementById(\"temp_offset_value\");\r\n"
"          var coldLight = document.getElementById(\"desired_cold\");\r\n"
"          var valueColdLight = document.getElementById(\"desired_cold_value\");\r\n"
"          var neutralLight = document.getElementById(\"desired_neutral\");\r\n"
"          var valueNeutralLight = document.getElementById(\"desired_neutral_value\");\r\n"
"          var warmLight = document.getElementById(\"desired_warm\");\r\n"
"          var valueWarmLight = document.getElementById(\"desired_warm_value\");\r\n"
"          var blueLight = document.getElementById(\"desired_blue\");\r\n"
"          var valueBlueLight = document.getElementById(\"desired_blue_value\");\r\n"
"	            $.ajax({ \r\n"
"	            	type: 'GET', \r\n"
"	            	contentType: 'application/json; charset=utf-8',\r\n"
"	            	url: '/fishtank.json', \r\n"
"	            	data: {}, \r\n"
"	            	dataType: 'json',\r\n"
"	            	success: function (data) {\r\n"
"                  desiredTemp.value=data.fishtanksettings.desired_temp;\r\n"
"                  valueDesiredTemp.innerHTML=data.fishtanksettings.desired_temp;\r\n"
"                  tempOffset.value=data.fishtanksettings.temp_offset;\r\n"
"                  valueTempOffset.innerHTML=data.fishtanksettings.temp_offset;\r\n"
"                  coldLight.value=data.fishtanksettings.desired_cold;\r\n"
"                  valueColdLight.innerHTML = data.fishtanksettings.desired_cold;\r\n"
"                  neutralLight.value=data.fishtanksettings.desired_neutral;\r\n"
"                  valueNeutralLight.innerHTML=data.fishtanksettings.desired_neutral;\r\n"
"                  warmLight.value=data.fishtanksettings.desired_warm;\r\n"
"                  valueWarmLight.innerHTML=data.fishtanksettings.desired_warm;\r\n"
"                  blueLight.value=data.fishtanksettings.desired_blue;\r\n"
"                  valueBlueLight.innerHTML=data.fishtanksettings.desired_blue;\r\n"
"                  document.getElementById(\"dn\"+data.fishtanksettings.daynight).checked = true;\r\n"
"	            	}\r\n"
"	          	});\r\n"
"          desiredTemp.oninput = function() {\r\n"
"              valueDesiredTemp.innerHTML = this.value;\r\n"
"          }\r\n"
"          tempOffset.oninput = function() {\r\n"
"              valueTempOffset.innerHTML = this.value;\r\n"
"          }\r\n"
"          coldLight.oninput = function() {\r\n"
"              valueColdLight.innerHTML = this.value;\r\n"
"          }\r\n"
"          neutralLight.oninput = function() {\r\n"
"              valueNeutralLight.innerHTML = this.value;\r\n"
"          }\r\n"
"          warmLight.oninput = function() {\r\n"
"              valueWarmLight.innerHTML = this.value;\r\n"
"          }\r\n"
"          blueLight.oninput = function() {\r\n"
"              valueBlueLight.innerHTML = this.value;\r\n"
"          }\r\n"
"        })\r\n"
"      </script>\r\n"
"    </head>\r\n"
"    <body>\r\n"
"        <h2>Aquarium Controller</h2>\r\n"
"        <form method=\"post\" action=\"\">\r\n"
"        <table>\r\n"
"            <tr>\r\n"
"                <td align=\"left\"><strong>Desired water temp:</strong></td>\r\n"
"                <td align=\"right\"><span id=\"desired_temp_value\" style=\"font-weight:bold;color:#4CAF50\">0</span>°C</td>\r\n"
"                <td class=\"slidecontainer\">\r\n"
"                  <input type=\"range\" min=\"20\" max=\"30\" value=\"\" class=\"slider\" id=\"desired_temp\" name=\"desired_temp\">\r\n"
"                </td>\r\n"
"            </tr>\r\n"
"            <tr>\r\n"
"                <td align=\"left\"><strong>Maximum okay offset:</strong></td>\r\n"
"                <td align=\"right\"><span id=\"temp_offset_value\" style=\"font-weight:bold;color:#4CAF50\">0.0</span>°C</td>\r\n"
"                <td class=\"slidecontainer\">\r\n"
"                  <input type=\"range\" min=\"0\" max=\"5\" value=\"\" step=\"0.1\" class=\"slider\" id=\"temp_offset\" name=\"temp_offset\">\r\n"
"                </td>\r\n"
"            </tr>\r\n"
"              <tr>\r\n"
"                <td align=\"left\"><strong>Max cold white intensity:</strong></td>\r\n"
"                <td align=\"right\"><span id=\"desired_cold_value\" style=\"font-weight:bold;color:#4CAF50\">0</span>%</td>\r\n"
"                <td class=\"slidecontainer\">\r\n"
"                  <input type=\"range\" min=\"1\" max=\"100\" value=\"\" class=\"slider\" id=\"desired_cold\" name=\"desired_cold\">\r\n"
"                </td>\r\n"
"            </tr>\r\n"
"            <tr>\r\n"
"                <td align=\"left\"><strong>Max neutral white intensity:</strong></td>\r\n"
"                <td align=\"right\"><span id=\"desired_neutral_value\" style=\"font-weight:bold;color:#4CAF50\">0</span>%</td>\r\n"
"                <td class=\"slidecontainer\">\r\n"
"                  <input type=\"range\" min=\"1\" max=\"100\" value=\"\" class=\"slider\" id=\"desired_neutral\" name=\"desired_neutral\">\r\n"
"                </td>\r\n"
"            </tr>\r\n"
"            <tr>\r\n"
"                <td align=\"left\"><strong>Max warm white intensity:</strong></td>\r\n"
"                <td align=\"right\"><span id=\"desired_warm_value\" style=\"font-weight:bold;color:#4CAF50\">0</span>%</td>\r\n"
"                <td class=\"slidecontainer\">\r\n"
"                  <input type=\"range\" min=\"1\" max=\"100\" value=\"\" class=\"slider\" id=\"desired_warm\" name=\"desired_warm\">\r\n"
"                </td>\r\n"
"            </tr>\r\n"
"            <tr>\r\n"
"                <td align=\"left\"><strong>Max blue light intensity:</strong></td>\r\n"
"                <td align=\"right\"><span id=\"desired_blue_value\" style=\"font-weight:bold;color:#4CAF50\">0</span>%</td>\r\n"
"                <td class=\"slidecontainer\">\r\n"
"                  <input type=\"range\" min=\"1\" max=\"100\" value=\"\" class=\"slider\" id=\"desired_blue\" name=\"desired_blue\">\r\n"
"                </td>\r\n"
"            </tr>\r\n"
"            <tr>\r\n"
"                <td align=\"left\"><strong>Day/Night mode:</strong></td>\r\n"
"                <td></td>\r\n"
"                <td align=\"left\">\r\n"
"                  <div class='switch'><div class='mode'>\r\n"
"                      <input id='dn0' name='daynight' type='radio' value='0'>\r\n"
"                      <label for='dn0'>Auto</label>\r\n"
"                    </div><div class='mode'>\r\n"
"                      <input id='dn1' name='daynight' type='radio' value='1'>\r\n"
"                      <label for='dn1'>Day</label>\r\n"
"                    </div><div class='mode'>\r\n"
"                      <input id='dn2' name='daynight' type='radio' value='2'>\r\n"
"                      <label for='dn2'>Night</label>\r\n"
"                    </div>\r\n"
"                  </div>\r\n"
"                </td>\r\n"
"            </tr>\r\n"
"            <tr>\r\n"
"                <td align=\"left\"><a id=\"backbutton\" href=\"/\"> Back to Status </a></td>\r\n"
"                <td align=\"left\"></td>\r\n"
"                <td align=\"left\"><input type=\"submit\" name=\"submit\" value=\"Save\" /></td>\r\n"
"            <tr>\r\n"
"        </table>\r\n"
"</form>\r\n";
#endif
